pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = 'docker-hub-creds'
        DOCKER_IMAGE_NAME = 'jaguil24/comp367-webapp'
        DOCKER_IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/jaguil24/Lab3.git'
            }
        }

        stage('Build Maven Project') {
            steps {
                bat '''
                    cd webApp/comp367-webapp
                    "C:\\Program Files\\Jenkins\\apache-maven-3.9.9\\bin\\mvn" clean install
                '''
            }
        }

        stage('Docker Login') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        echo "Successfully logged in to Docker Hub"
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat '''
                        cd webApp/comp367-webapp
                        docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    bat "docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                }
            }
        }
    }
}
